package com.carolinapinzon.java.web;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Arrays;

import javax.servlet.ServletException;
import javax.servlet.ServletOutputStream;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.json.JSONObject;

/**
 * Servlet implementation class UserSerlvet
 */
@WebServlet("/UserSerlvet")
public class UserSerlvet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final String URL = "jdbc:postgresql://138.197.76.68:5432/recreovias?user=postgres&password=postgres&sslmode=require";
    private static final String[] barrios = {"CONEJERA", "CASABLANCA SUBA", "TORCA", "TUNA", "TIBABITA", "CANAIMA", "LAS MERCEDES SUBA", "SAN JOSE DE BAVARIA", "MIRANDELA", "TIBABITA", "BUENAVISTA", "LA ESTRELLITA", "EL CEREZO", "VERBENAL SAN ANTONIO", "EL VERVENAL", "HORIZONTES NORTE", "VEREDA SUBA CERROS II", "NUEVA ZELANDIA", "VILLA DEL PRADO", "VEREDA TIBABUYES", "IRAGUA", "RINCON DE SANTA INES", "SABANA DE TIBABUYES NORTE", "DELMONTE", "TUNA BAJA", "SAN JOSE V SECTOR", "SAN JOSE DE USAQUEN", "EL ROCIO NORTE", "SAN ANTONIO NOROCCIDENTAL", "TUNA ALTA", "SAN ANTONIO NORTE", "TIBABUYES", "SALITRE SUBA", "VILLA HERMOSA", "PINOS DE LOMBARDIA", "CASABLANCA SUBA", "BARRANCAS ORIENTAL", "PORTALES DEL NORTE", "LA URIBE", "EL REDIL", "EL PINO", "CAMPANELLA", "TIBABUYES OCCIDENTAL", "BRITALIA", "SABANA DE TIBABUYES", "LA GRANJA NORTE", "GRANADA NORTE", "BILBAO", "SAN CARLOS DE SUBA", "EL TOBERIN", "VEREDA SUBA CERROS", "LOMBARDIA", "SANTA RITA DE SUBA", "SUBA URBAN0", "LA PRADERA NORTE", "BOSQUES DE SAN JORGE", "SANTA TERESA", "EL POA", "BERLIN", "GILMAR", "SAN PEDRO", "TIBABUYES UNIVERSAL", "LAS FLORES", "PUERTA DEL SOL", "CANTAGALLO", "TOSCANA", "LISBOA", "LAS ORQUIDEAS", "EL PLAN", "LA CITA", "LA GAITANA", "VILLA MARIA", "TIBABUYES", "SANTA CECILIA", "SAN CRISTOBAL NORTE", "ESTRELLA DEL NORTE", "COSTA AZUL", "EL DORADO", "MAZUREN", "BOSQUE DE PINOS", "LA CHUCUA", "LA LIBERIA", "ESCUELA DE CARABINEROS", "NUEVA TIBABUYES", "VILLA ELISA", "LAS MARGARITAS", "POTRERILLO", "BARRANCAS NORTE", "ALTOS DE CHOZICA", "AURES II", "STA. C. PUENTE NORTE", "SANTA HELENA", "LAGO DE SUBA", "AURES", "CIUDADELA COLSUBSIDIO", "VICTORIA NORTE", "CAOBOS SALAZAR", "EL CORTIJO", "BARRANCAS", "NIZA SUBA", "VEREDA SUBA NARANJOS", "ATENAS", "TTES DE COLOMBIA", "BOSQUE DE PINOS I", "IBERIA", "EL RINCON NORTE", "CEDRO SALAZAR", "PRADO PINZON", "ENGATIVA EL DORADO", "EL GACO", "LECH WALESA", "VEREDA SUBA RINCON", "LOS CEDROS", "SAN CAYETANO", "LOS NARANJOS", "SAN JOSE DEL PRADO", "ACACIAS USAQUEN", "CIUDAD JARDIN NORTE", "EL RINCON", "EL CEDRO", "LOS CEDROS ORIENTAL", "BOLIVIA ORIENTAL", "CEDRO NARVAEZ", "RINCON DE SUBA", "EL CONTADOR", "PRADO VERANIEGO NORTE", "CEDRITOS", "CIUDAD HUNZA", "GRAN GRANADA", "BOCHICA II", "CIUDAD BACHUE", "VEREDA CENTRO ENGATIVA II", "VILLAS DE GRANADA I", "BOLIVIA", "PRADO VERANIEGO", "CIUDAD BACHUE I ETAPA", "LAS VILLAS", "CENTRO ENGATIVA", "NIZA NORTE", "ALMIRANTE COLON", "LISBOA", "LA CALLEJA", "CLUB DE LOS LAGARTOS", "ENGATIVA ZONA URBANA", "VILLAS DE GRANADA", "PRADO VERANIEGO SUR", "LUIS CARLOS GALAN", "COUNTRY CLUB", "CENTRO ENGATIVA II", "GARCES NAVAS", "LOS CEREZOS", "GARCES NAVAS SUR", "GARCES NAVAS ORIENTAL", "BOCHICA", "SABANA DEL DORADO", "CANODROMO", "QUIRIGUA", "AEROPUERTO EL DORADO", "LA CAROLINA", "GINEBRA", "PRIMAVERA", "VILLA AMALIA", "BELLA SUIZA", "EL CEDRO", "PARAMO", "VEREDA CENTRO ENGATIVA", "EL MADRIGAL", "LA SERENA", "BATAN", "NIZA SUR", "BOLIVIA", "VILLA GLADYS", "PARIS GAITAN", "ALAMOS", "PARIS", "SN. ANTONIO ENGATIVA", "SANTA BARBARA OCCIDENTAL", "CHARCO", "VILLA SAGRARIO", "EL MINUTO DE DIOS", "SAN GABRIEL NORTE", "MONACO", "SAN ANTONIO URBANO", "VILLA DEL MAR", "FLORENCIA", "SANTA BARBARA CENTRAL", "POTOSI", "SANTA BARBARA ORIENTAL", "AUTOPISTA MEDELLIN", "SANTA MONICA", "LA GRANJA", "EL MUELLE", "PUENTE LARGO", "BRISAS ALDEA-FONTIBON", "LOS ALAMOS", "LOS ANGELES", "LA SOLEDAD NORTE", "SAN PATRICIO", "FLORIDA BLANCA", "SANTA ROSA", "PUENTE GRANDE", "JULIO FLOREZ", "USAQUEN", "SANTA MARIA", "PASADENA", "TABORA", "ESTORIL", "EL CHARCO", "MOLINOS NORTE", "ANDES NORTE", "BONANZA", "SANTA  HELENITA", "EL REFUGIO", "LOS ALAMOS", "SANTA ANA OCCIDENTAL", "SAN PABLO JERICO", "SANTA BIBIANA", "LAS FERIAS OCCIDENTAL", "BOYACA", "SANTA ANA", "RINCON DEL CHICO", "ATAHUALPA", "LOS ANDES", "VILLA LUZ", "SAN JOSE DE FONTIBON", "VERSALLES FONTIBON", "RIONEGRO", "LA CASTELLANA", "ESCUELA DE INFANTERIA", "LAS FERIAS", "PALO BLANCO", "ESCUELA DE CABALLERIA I", "CHICO NORTE III SECTOR", "BELEN FONTIBON", "LA CABANA", "PUERTA DE TEJA", "ENTRERIOS", "PARAMO I", "CHICO NORTE II SECTOR", "EL REAL", "ESCUELA MILITAR", "METROPOLIS", "VILLA CARMENZA", "LA ESTRADA", "EL LAUREL", "SANTA CECILIA", "SAN IGNACIO", "EL CARMEN FONTIBON", "EL TINTAL", "EL ENCANTO", "JORGE ELIECER GAITAN", "SIMON BOLIVAR", "ESCUELA DE CABALLERIA II", "SANTA CECILIA", "CHICO NORTE", "SAN JOAQUIN", "BELLAVISTA OCCIDENTAL", "CENTRO FONTIBON", "SEMINARIO", "FERROCAJA FONTIBON", "CENTRO ENGATIVA", "LA LIBERTAD", "NORMANDIA OCCIDENTAL", "POLO CLUB", "EL CHICO", "LA PATRIA", "SAN FERNANDO OCCIDENTAL", "JOSE JOAQUIN VARGAS", "LA CABANA", "ANTIGUO COUNTRY", "LA ESTRADITA", "SAN LUIS ALTOS DEL CABO", "VILLEMAR", "SAN FERNANDO", "BOSQUE DE MODELIA", "DOCE DE OCTUBRE", "BOSQUE POPULAR", "EL TINTAL", "VEREDA EL TINTAL", "PORCIUNCULA", "LA PAZ", "COLOMBIA", "OSORIO", "LA ESPERANZA SUR", "SIETE DE AGOSTO", "CONCEPCION NORTE", "PABLO VI NORTE", "BELLAVISTA", "QUINTA CAMACHO", "EL VERGEL", "EL ROSARIO", "TERMINAL DE TRANSPORTES", "SALITRE OCCIDENTAL", "RAFAEL URIBE", "OSORIO", "EL SALITRE", "VERGEL OCCIDENTAL", "BENJAMIN HERRERA", "LA ESPERANZA", "QUINTA MUTIS", "FRANCO", "EL VERGEL ORIENTAL", "MUEQUETA", "INTERINDUSTRIAL", "GALAN", "EMAUS", "OSORIO XXIII", "BAQUERO", "PAULO VI", "CHAPINERO NORTE", "LAS ACACIAS", "CIUDAD SALITRE NOR-ORIENTAL", "LA PAMPA", "NICOLAS DE FEDERMAN", "LAS ACACIAS", "VISION DE ORIENTE", "CAMPIN OCCIDENTAL", "EL JAZMIN", "CAMPIN", "EL CORZO", "LA ESMERALDA", "GRANADA", "SAN LUIS", "NUEVO TECHO", "MONTEVIDEO", "INGEMAR ORIENTAL", "CHAPINERO OCCIDENTAL", "CENTRO ADMINISTRATIVO OCCIDENT", "LOS ALMENDROS", "OSORIO XII", "CHAPINERO CENTRAL", "MARIA CRISTINA", "OSORIO", "VILLA ALSACIA", "JUAN XXIII", "CIUDAD SALITRE SUR-ORIENTAL", "OSORIO DIEZ", "GRANJAS DE TECHO", "CALANDAIMA", "RAFAEL NUNEZ", "LA SALLE", "SAN BERNARDINO II", "SAN BERNARDINO XVI", "PARCELA EL PORVENIR", "VILLA ALSACIA", "EL PARAISO", "COOPERATIVA DE SUB-OFICIALES", "GALERIAS", "CANAVERALEJO", "CENTRO INDUSTRIAL", "CIUDAD UNIVERSITARIA", "PATIO BONITO III", "BANCO CENTRAL", "CIUDAD DE CALI", "SAN BERNARDINO XXV", "DINDALITO", "EL PARAISO BOSA", "BOSQUE CALDERON", "CASTILLA", "BELALCAZAR", "HOYA TEUSACA", "INGEMAR", "PATIO BONITO", "BAVARIA", "CAMPO HERMOSO", "QUESADA", "TAIRONA", "MARSELLA", "SAN BERNARDINO XVII", "SIBERIA", "ALFONSO LOPEZ", "LUSITANIA", "OSORIO", "SAN BERNARDINO XIX", "SANTA FE BOSA", "MARLY", "PROVIVIENDA OCCIDENTAL", "QUINTA PAREDES", "PARDO RUBIO", "PATIO BONITO II", "PIO XII", "LAS MARGARITAS", "PUENTE ARANDA", "DINDALITO", "ORTEZAL", "PALERMO", "SALAZAR GOMEZ", "LAS DOS AVENIDAS", "LAS MARGARITAS", "SAUCEDAL", "EL RECUERDO", "SIBERIA CENTRAL", "DINTALITO", "CIUDAD KENNEDY NORTE", "LA CABANA", "CORABASTOS", "LA SOLEDAD", "BRASIL", "LLANO GRANDE", "SANTA TERESITA", "BATALLON CALDAS", "TINTALITO", "ACEVEDO TEJADA", "LAS AMERICAS", "SUCRE", "CENTRO NARINO", "EL PORTAL DEL BRASIL", "CHUCUA DE LA VACA III", "BRASILIA", "MANDALAY", "CATALUNA", "LA LIBERTAD", "LA MAGDALENA", "CHUCUA DE LA VACA II", "HIPOTECHO", "SAN BERNARDINO XXII", "EL PARAISO", "SAN MARTIN", "GRAN AMERICA", "BETANIA", "TECHO", "CHUCUA DE LA VACA I", "HIPOTECHO SUR", "LA PRADERA", "SAGRADO CORAZON", "LA TRINIDAD", "CIUDAD KENNEDY", "GRAN BRITALIA I", "SAN RAFAEL INDUSTRIAL", "SAN ANTONIO", "ESCOCIA", "VILLA NELLY III SECTOR", "CIUDAD KENNEDY CENTRAL", "GORGONZOLA", "EL EJIDO", "CHICALA", "FLORIDA", "SAN FRANCISCO", "VILLAS DEL PROGRESO", "CIUDAD KENNEDY OCCIDENTAL", "SAN GABRIEL", "INDUSTRIAL CENTENARIO", "PARQUE NACIONAL", "TEUSAQUILLO", "JORGE URIBE BOTERO", "CHICO SUR", "HIPOTECHO OCCIDENTAL", "LA FLORIDA OCCIDENTAL", "COLON", "CIUDAD KENNEDY ORIENTAL", "CUNDINAMARCA", "ESCOCIA", "USATAMA", "CIUDAD KENNEDY SUR", "ESTRELLA", "EL DANUBIO AZUL", "GALAN", "LA INDEPENDENCIA", "BOSA NOVA EL PORVENIR", "SAN BERNARDINO XVIII", "PARQUE NACIONAL ORIENTAL", "SAN RAFAEL", "LA MERCED", "GRAN BRITALIA", "EL REMANSO", "ESTACION CENTRAL", "SAMPER MENDOZA", "SAMPER", "COLSEGUROS", "SAN PEDRO", "EL CARMELO", "PASTRANA", "SANTA FE", "CASABLANCA SUR", "BOSANOVA", "LOS EJIDOS", "BARCELONA", "ARMENIA", "PALOQUEMAO", "LA PERSEVERANCIA", "SAN MARTIN", "ISLANDIA", "LOS SAUCES", "LOS LAURELES", "PROVIVIENDA OCCIDENTAL", "LA PAZ BOSA", "TIMIZA", "PROVIVIENDA", "CASABLANCA", "PENSILVANIA", "PRIMAVERA OCCIDENTAL", "PROVIVIENDA NORTE", "PROVIVIENDA ORIENTAL", "SAN DIEGO-BOSA", "GRAN COLOMBIANO", "SAN DIEGO", "LA MACARENA", "EL JARDIN", "CLASS", "LA CAMELIA", "EL LISTON", "ARGELIA II", "LA ALAMEDA", "MONTES", "TOCAREMA", "TIMIZA B", "LA FAVORITA", "ROMA", "CATALINA", "RICAURTE", "BOSA", "ANTONIA SANTOS", "TIMIZA A", "PASO ANCHO", "TIBANA", "JAQUELINE", "JORGE GAITAN CORTES", "EL RUBI", "LAS NIEVES", "SAN EUSEBIO", "BOSQUE IZQUIERDO", "LA CAMPINA", "COMUNEROS", "LA ESTANZUELA", "EL PROGRESO", "GUALOCHE", "SANTA MATILDE", "AUTOPISTA SUR", "SANTA ISABEL", "DELICIAS", "NUEVA GRANADA BOSA", "SANTA INES", "TUNDAMA", "AUTOPISTA MUZU", "LA CATEDRAL", "OSPINA PEREZ", "LA ESTACION-BOSA", "SANTA ISABEL SUR", "CENTRO ADMINISTRATIVO", "AUTOPISTA MUZU 0RIENTAL", "GUADALUPE", "EL VERGEL", "LA CONCORDIA", "OSPINA PEREZ SUR", "SENA", "LA FRAGUA", "EGIPTO", "SAN FRANCISCO RURAL", "EDUARDO SANTOS", "SAN BERNARDO", "LA ESTANCIA", "PRIMAVERA II", "MADELENA", "RAFAEL ESCAMILLA", "EDUARDO FREI", "ISLA DEL SOL", "RINCON DE LA VALVANERA", "GALICIA", "BARLOVENTO", "VENECIA OCCIDENTAL", "SANTANDER", "VENECIA", "SANTA BARBARA", "LA FRAGUITA", "VILLA MAYOR ORIENTAL", "SANTANDER SUR", "RESTREPO OCCIDENTAL", "ESCUELA GENERAL SANTANDER", "SAN ANTONIO", "BELEN", "NUEVO MUZU", "VILLA MAYOR", "LAS CRUCES", "MARIA CANO", "LA PRIMAVERA I", "LA HORTUA", "ISMAEL PERDOMO", "EL GUAVIO", "LOS TRES REYES", "FATIMA", "LOURDES", "SEVILLA", "RESTREPO", "ATLANTA", "El PENON DEL CORTIJO", "BRAVO PAEZ", "LA PENA", "LOS LACHES", "SANTIAGO PEREZ", "MODELO SUR", "POLICARPA", "MURILLO TORO", "INGLES", "LIBERTADOR", "GIRARDOT", "RINCON DE GALICIA", "CIUDAD BERNA", "CENTENARIO", "EL MIRADOR DE LA ESTANCIA", "EL ENSUENO", "MUZU", "CALVO SUR", "PERDOMO ALTO", "CLARET", "EL ROCIO", "LAS BRISAS", "SAN VICENTE FERRER", "RAMIREZ", "SAMORE", "CARACAS", "CIUDAD JARDIN SUR", "SIERRA MORENA", "EL CARMEN", "OLAYA", "NARINO SUR", "QUIROGA", "EL DORADO", "SIERRA MORENA", "QUIROGA CENTRAL", "BUENOS AIRES", "SAN ANTONIO DEL MIRADOR", "SANTO DOMINGO", "SAN JAVIER", "QUIROGA SUR", "VERONA", "SOCIEGO", "LA CORUNA", "SAN JOSE SUR", "QUINTA RAMOS", "SANTA LUCIA", "TUNAL ORIENTAL", "SIERRA MORENA", "SANTA ANA SUR", "VITELMA", "SANTA VIVIANA", "LA MARIA", "GUSTAVO RESTREPO", "BELLAVISTA", "HOYA SAN CRISTOBAL", "ARBORIZADORA BAJA", "SOCIEGO SUR", "VELODROMO", "PARQUE EL TUNAL", "GRANJAS SAN PABLO", "HOSPITAL SAN CARLOS", "LA PRADERA", "20 DE JULIO", "JERUSALEN", "SAN CRISTOBAL SUR", "A.S.D", "SAN JORGE SUR", "LAS BRISAS", "PRIMERO DE MAYO", "CANDELARIA LA NUEVA", "EL CHIRCAL SUR", "ARBORIZADORA ALTA", "GRANJAS DE SANTA SOFIA", "GRANADA SUR", "POTOSI", "CIUDAD BOLIVAR", "MARCO FIDEL SUAREZ", "SAN LUIS", "RONDA", "MONTE CARLO", "SAN BLAS", "ARBORIZADORA ALTA", "VILLA CANDELARIA", "SAN CARLOS", "LAS MERCEDES", "SURAMERICA", "MARCO FIDEL SUAREZ I", "MOLINOS DE ORIENTE", "LA RESURRECCION", "MONTEBELLO", "ARBORIZADORA ALTA", "SAN ISIDRO", "SAN PEDRO", "EL TRIANGULO", "TIBAQUE", "ARBORIZADORA ALTA", "LOS LAURELES I", "SAN FRANCISCO", "LAS ACACIAS", "SAN BENITO", "CORDOBA", "BARCELONA SUR", "ARBOLEDA SUR", "CARMEN DEL SOL", "A.S.D", "SAN BLAS II", "LAS LOMAS", "TUNJUELITO", "JUAN JOSE RONDON", "AGUAS CLARAS", "BELLO HORIZONTE", "VILLAS DE LOS ALPES I", "SANTA INES SUR", "EL PLAYON", "PUERTO RICO", "CERROS DE ORIENTE", "GUIPARMA", "MEISSEN", "RAMAJAL", "QUIBA BAJO", "VILLA DE LOS ALPES", "LUCERO ALTO", "MILLAN", "ABRAHAM LINCOLN", "LAS GUACAMAYAS", "ATENAS", "MOLINOS DEL SUR", "COMPARTIR", "CALLEJON SANTA BARBARA", "AREA ARTILLERIA", "LOS ALPES", "GIBRALTAR SUR", "SAN VICENTE", "EL MIRADOR", "JUAN PABLO II", "LOS MOLINOS", "SUMAPAZ", "MEXICO", "CENTRAL DE MEZCLAS", "MARRUECOS", "SAN MARTIN SUR", "PARAISO QUIBA", "LA VICTORIA", "LUCERO DEL SUR", "LA PICOTA", "VILLA GLORIA", "VILLAS EL DIAMANTE", "ALTOS DEL ZIPA", "BELLAVISTA SUR", "SAN AGUSTIN", "SAN RAFAEL", "NUEVA GLORIA", "DIANA TURBAY CULTIVOS", "PORVENIR", "DANUBIO", "CEDRITOS DEL SUR", "CORDILLERA DEL SUR", "QUINDIO", "DANUBIO II", "LA FISCALA NORTE", "EL PINAR", "EL MOCHUELO", "EL TESORO", "EL MOCHUELO BAJO", "LA ARBOLEDA", "EL MINUTO DE MARIA", "ARABIA", "LOS LIBERTADORES", "QUIBA URBAN0", "LA BELLEZA", "LAS GAVIOTAS", "LA FISCALA", "EL NEVADO", "SAN RAFAEL USME", "NUEVA DELLY", "ALASKA", "A.S.D.", "JUAN REY ( LA PAZ )", "CHIGUAZA", "LA AURORA", "DUITAMA", "NUEVO SAN ANDRES", "YOMASA", "BARRANQUILLITA", "QUIBA ALTO", "CIUDAD LONDRES", "BOLONIA", "GRANADA SUR", "SANTA LIBRADA NORTE", "SANTA LIBRADA", "LOS OLIVARES", "SALAZAR USME", "TUNJUELITO", "JUAN REY SUR", "LA ANDREA", "SAN JUAN BAUTISTA", "LA CABANA", "LA CABANA", "MARICHUELA", "EL CURUBO", "LILIANA", "LAGUNITAS", "GRAN YOMASA", "LA ESPERANZA SUR", "MONTE BLANCO", "SAN PEDRO SUR", "EL BOSQUE", "CHUNIZA", "EL BOSQUE CENTRAL", "EL VIRREY", "CHAPINERITO", "CHARALA", "TIBAQUE SUR", "SAN FELIPE USME", "YOMASA NORTE", "TIHUAQUE", "TOCAIMITA ORIENTAL", "VILLA DIANA", "LA REFORMA", "LOS SOCHES", "MOCHUELO ALTO", "PEPINITOS", "DESARROLLO BRAZUELOS", "SANTA SOFIA", "NORMANDIA", "LA LAGUNA FONTIBON", "EL REFUGIO", "LA CABRERA", "MODELIA OCCIDENTAL", "PARQUE POPULAR SALITRE", "EL TINTAL CENTRAL", "POPULAR MODELO", "ONCE DE NOVIEMBRE", "MODELIA", "GUADUAL FONTIBON", "JARDIN BOTANICO", "JUAN XXIII", "SAN ISIDRO", "EL RETIRO", "LAGO GAITAN", "LA AURORA", "EL BAGAZAL", "CENTRO ENGATIVA", "LA MERCED NORTE", "ESPARTILLAL", "ALCAZARES NORTE", "EL NOGAL", "SAN FELIPE", "LA ESPERANZA NORTE", "PARQUE DISTRITAL SALITRE", "CAPELLANIA", "CAMPO EUCARISTICO", "ALCAZARES", "EL TINTAL A.S.D.", "SAN MIGUEL", "LOS ROSALES", "VEREDA EL TINTAL II", "JOSE ANTONIO GALAN", "CATALINA II", "LA SABANA", "JIMENEZ DE QUESADA", "SAN PABLO BOSA", "EL RETAZO", "SAN BERNARDINO I", "ALQUERIA LA FRAGUA N.", "TEJAR", "SAN VICTORINO", "LA CAPUCHINA", "LAS AGUAS", "LA CECILIA", "LA PEPITA", "BOCHICA", "CHARLES DE GAULLE", "REMANSO", "VOTO NACIONAL", "NUEVA YORK", "RENANIA URAPANES", "SANTA CATALINA", "VILLA ANNY", "VERACRUZ", "VERAGUAS", "ALCALA", "REMANSO SUR", "JOSE MARIA CARBONEL", "OLARTE", "ALQUERIA LA FRAGUA", "BOITA", "LA ASUNCION", "VILLA DEL RIO", "CEMENTERIO JARDINES APOGEO", "ANDALUCIA II", "ALQUERIA", "BOSQUE DE LOS ALPES", "LA ALAMEDA", "BELLAVISTA LUCERO ALTO", "DIANA TURBAY", "ALTOS DEL POBLADO", "SAN JOSE SURORIENTAL", "LA GLORIA OCCIDENTAL", "NUEVA ESPERANZA", "LOS ALPES SUR", "LA GLORIA ORIENTAL", "BELLA FLOR SUR", "CANADA O GUIRA", "ESTRELLA DEL SUR", "QUINTAS DEL SUR", "DIANA TURBAY ARRAYANES", "LA PICOTA ORIENTAL", "BELLA FLOR", "SOTAVENTO", "MORALBA", "ALTAMIRA", "ARRAYANES", "NACIONES UNIDAS", "EL MOCHUELO ORIENTAL", "LA TORRE", "LOS ARRAYANES II", "CASA DE TEJA", "PALERMO SUR", "LA PAZ", "ALTOS DEL ZUQUE", "PUENTE COLORADO", "SANTA RITA SUR ORIENTAL", "VILLABEL", "QUIBA", "EL PARAISO", "JUAN JOSE RONDON", "LAS VIOLETAS", "SERRANIAS", "COMUNEROS", "SERRANIAS I", "EL NUEVO PORTAL II", "EL PROGRESO USME", "LOS ARRAYANES", "TOCAIMITA SUR", "LA ORQUIDEA DE USME", "BRAZUELOS OCCIDENTAL", "EL NUEVO PORTAL", "USMINIA", "LA ESPERANZA DE USME", "ANTONIO JOSE DE SUCRE", "A.S.D.", "PUERTA AL LLANO", "VILLA ISRAEL", "VILLA ANITA", "EL REFUGIO I", "EL PORTAL DEL DIVINO", "EL UVAL", "LA REQUILINA", "EL BOSQUE SUR ORIENTAL", "CENTRO USME"};
    private static final int[] estratoBarrios = {2, 1, 3, 1, 1, 2, 0, 4, 3, 3, 2, 1, 4, 3, 3, 2, 2, 3, 3, 2, 4, 2, 2, 0, 2, 0, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 1, 3, 2, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 2, 3, 2, 1, 3, 2, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2, 3, 4, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 3, 2, 3, 2, 1, 3, 2, 2, 2, 4, 4, 2, 3, 6, 4, 3, 1, 3, 4, 2, 4, 3, 0, 2, 2, 2, 4, 2, 2, 3, 4, 3, 2, 0, 4, 2, 4, 2, 4, 4, 3, 2, 2, 2, 2, 1, 3, 3, 3, 2, 3, 2, 5, 2, 4, 4, 2, 2, 3, 3, 1, 4, 2, 2, 3, 3, 3, 2, 2, 3, 1, 0, 5, 3, 2, 2, 5, 3, 2, 2, 3, 2, 4, 5, 2, 2, 2, 3, 2, 2, 4, 1, 3, 2, 2, 4, 2, 2, 3, 5, 4, 5, 2, 2, 3, 2, 4, 1, 3, 2, 2, 6, 3, 3, 2, 3, 4, 3, 4, 3, 4, 1, 5, 3, 3, 3, 2, 2, 4, 2, 4, 3, 3, 4, 5, 2, 4, 3, 2, 3, 3, 4, 3, 3, 3, 3, 5, 3, 3, 1, 2, 2, 5, 3, 2, 3, 3, 3, 3, 3, 2, 3, 1, 3, 3, 3, 2, 3, 5, 3, 3, 3, 3, 2, 1, 3, 4, 3, 6, 3, 3, 4, 3, 5, 3, 2, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 2, 3, 3, 3, 3, 6, 4, 2, 3, 2, 2, 3, 1, 3, 2, 3, 3, 3, 0, 1, 3, 1, 1, 5, 1, 3, 4, 3, 5, 1, 2, 3, 0, 3, 3, 1, 3, 1, 4, 4, 4, 2, 0, 1, 3, 0, 2, 0, 3, 2, 2, 2, 2, 2, 1, 0, 2, 3, 4, 2, 1, 1, 3, 2, 2, 3, 1, 0, 0, 2, 3, 2, 0, 2, 2, 4, 2, 4, 0, 3, 2, 3, 2, 3, 2, 3, 1, 1, 3, 0, 2, 1, 1, 4, 2, 3, 3, 2, 3, 1, 3, 2, 2, 4, 2, 2, 2, 2, 4, 1, 2, 3, 1, 1, 4, 2, 2, 4, 0, 2, 3, 3, 3, 2, 2, 2, 2, 3, 3, 2, 3, 2, 3, 1, 1, 2, 4, 2, 3, 2, 2, 3, 2, 3, 3, 2, 2, 2, 2, 2, 3, 1, 0, 1, 2, 3, 2, 3, 3, 0, 0, 4, 1, 2, 2, 0, 3, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 1, 0, 3, 3, 2, 2, 0, 3, 2, 3, 2, 2, 3, 2, 2, 2, 0, 3, 3, 0, 2, 3, 2, 2, 1, 3, 2, 2, 3, 3, 2, 3, 3, 3, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 3, 2, 2, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 1, 2, 2, 3, 2, 3, 1, 3, 1, 2, 2, 3, 2, 2, 3, 2, 2, 1, 3, 0, 2, 1, 2, 1, 2, 3, 3, 3, 2, 3, 2, 3, 3, 1, 3, 2, 3, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 3, 3, 1, 1, 2, 2, 2, 2, 3, 2, 3, 3, 3, 2, 1, 3, 3, 1, 1, 2, 3, 1, 3, 2, 1, 2, 1, 2, 2, 3, 1, 2, 3, 3, 2, 1, 1, 2, 2, 0, 1, 3, 2, 1, 3, 2, 3, 3, 3, 3, 1, 3, 2, 1, 3, 2, 1, 1, 2, 3, 2, 0, 2, 2, 1, 3, 1, 2, 1, 3, 1, 3, 2, 2, 1, 2, 2, 1, 1, 3, 2, 2, 1, 2, 1, 1, 2, 2, 3, 2, 1, 2, 3, 1, 3, 2, 1, 1, 0, 1, 2, 2, 2, 2, 2, 1, 1, 0, 1, 2, 2, 1, 0, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 2, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 3, 4, 3, 5, 5, 4, 2, 2, 3, 3, 3, 2, 1, 3, 2, 4, 4, 3, 5, 2, 3, 4, 3, 5, 3, 2, 0, 2, 0, 2, 1, 3, 6, 0, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 3, 2, 3, 3, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 3, 3, 2, 2, 2, 3, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1};
    
    /**
     * @see HttpServlet#HttpServlet()
     */
    public UserSerlvet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		String id = req.getParameter("id");
        //System.out.println(id);
        ServletOutputStream out = resp.getOutputStream();
        out.write(id.getBytes());
        out.flush();
        out.close();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		try {
            String body = getPostData(req);
            JSONObject obj = new JSONObject(body);
            ArrayList<String> columns = new ArrayList<String>();
            String id_auth = obj.getString("id_auth");
            String birthdateString = obj.getString("birthdate");
            String distanciasRecreovias = obj.getString("distancias");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
            LocalDate birthdate = LocalDate.parse(birthdateString, formatter);
            LocalDate now = LocalDate.now();
            long age = ChronoUnit.YEARS.between(birthdate, now);
            if(age < 30) {
                columns.add("edad_0");
            }
            else if (age < 60) {
                columns.add("edad_1");
            }
            else {
                columns.add("edad_2");
            }
            String sex = obj.getString("sex");
            columns.add(sex.toLowerCase());
            String barrio = obj.getString("barrio");
            int estrato = estratoBarrios[Arrays.asList(barrios).indexOf(barrio)];
            if(estrato <= 2) {
                columns.add("estrato_0_1_2");
            }
            else if(estrato <= 4) {
                columns.add("estrato_3_4");
            }
            else {
                columns.add("estrato_5_6");
            }
            String sqlQuery = "INSERT INTO matriz (";
            for(int i = 0; i < columns.size(); i++) {
                sqlQuery += columns.get(i) + ", ";
            }
            sqlQuery += "barrio, id_auth, recreovias_distancias) VALUES (";
            for(int i = 0; i < columns.size(); i++) {
                sqlQuery += "1, ";
            }
            sqlQuery += "'" + barrio + "', '" + id_auth + "', '" + distanciasRecreovias + "');"; 
            //System.out.println(sqlQuery);
            Connection conn = getConnection();
            Statement stmt = conn.createStatement();
            stmt.executeUpdate(sqlQuery);
            conn.close();

            resp.setContentType("application/json");
            PrintWriter out = resp.getWriter();;
            out.println("{");
            out.println("\"code\": \"OK\"");
            out.println("}");
            out.close();
        } catch(Exception e) {
            //System.out.println(e);
        }
	}
	
	public static String getPostData(HttpServletRequest req) {
        String response = "";
        try {
            BufferedReader reader = req.getReader();
            reader.mark(10000);

            String line = reader.readLine();
            while(line != null) {
                response += line + "\n";
                line = reader.readLine();
            }
            reader.reset();
            // do NOT close the reader here, or you won't be able to get the post data twice
        } catch(IOException e) {
            //System.out.println("getPostData couldn't.. get the post data" + e);  // This has happened if the request's reader is closed    
        }

        return response;
    }
	
	private static Connection getConnection() throws URISyntaxException, SQLException, ClassNotFoundException {
		Class.forName("org.postgresql.Driver");
		
		return DriverManager.getConnection(URL);
    }

}
